wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692534031.115084
    t:
      1:
      - 55
      - 86
      - 105
      2:
      - 55
      - 86
      - 105
      3:
      - 23
      4: 3.10.2
      5: 0.15.8
      8:
      - 3
      - 5
