wandb_version: 1

project:
  desc: null
  value: AI Agents Hackathon
entity:
  desc: null
  value: null
job_type:
  desc: null
  value: production
vector_store_artifact:
  desc: null
  value: zestt/AI Agents Hackathon/vector_store:latest
chat_prompt_artifact:
  desc: null
  value: zestt/AI Agents Hackathon/chat_prompt:latest
chat_temperature:
  desc: null
  value: 0
max_fallback_retries:
  desc: null
  value: 1
model_name:
  desc: null
  value: gpt-3.5-turbo-16k
eval_model:
  desc: null
  value: gpt-3.5-turbo-16k
eval_artifact:
  desc: null
  value: zestt/AI Agents Hackathon/generated_examples:v0
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692536901.636609
    t:
      1:
      - 49
      - 55
      - 86
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 86
      - 92
      - 95
      - 105
      3:
      - 16
      - 23
      - 24
      4: 3.10.2
      5: 0.15.8
      8:
      - 3
      - 5
    framework: huggingface
